---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-green
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        location / {
          try_files $uri /index.html;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      volumes:
      - name: webdata
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config-green
          items:
          - key: nginx.conf
            path: nginx.conf
      initContainers:
      - name: web-content
        image: busybox
        volumeMounts:
        - name: webdata
          mountPath: "/webdata"
        command: ["/bin/sh", "-c", 'echo "<h1><font color=Gree>GREEN APP</font></h1>" > /webdata/index.html']
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: webdata
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  type: ClusterIP
  selector:
    app: green
  ports:
  - port: 80
    targetPort: 80

